version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./html:/var/www/html
